name: Run Audio v2 Playwright Tests

on:
    push:
        branches:
            - main-staging
    pull_request:
        branches:
            - main-staging

jobs:
    run-audio-v2-tests:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v3

            - name: Set up Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: "22.4.1"

            - name: Install dependencies
              run: npm install

            - name: Install Playwright dependencies
              run: npx playwright install-deps

            - name: Install Playwright browsers
              run: npx playwright install chromium

            - name: Build dev version
              run: npm run build:dev

            - name: Start dev server
              run: npm start &

            - name: Wait for dev server to be ready
              run: npx wait-on http://localhost:1337

            - name: Run Audio v2 Playwright Tests
              run: npm run test:audioV2 -- --max-failures 10 --retries 0
              env:
                  BROWSER: "chromium"
